package dev.forgesworn.kithmoot.session

/** ForgeMoji 0.1.2, by TheCryptoDonkey; pinned source c9f53357de24fff682e8a234af183406a57757a6. */
data class FamiliarArt(val emoji: String, val slug: String, val keywords: String, val toneable: Boolean, val title: String = slug.replace('-', ' '), val category: String = "faces")
val FAMILIAR_ART = listOf(
    FamiliarArt("👍", "thumbs-up", "thumbs up yes good like", true, "Thumbs up", "Hands"),
    FamiliarArt("👎", "thumbs-down", "thumbs down no dislike", true, "Thumbs down", "Hands"),
    FamiliarArt("👋", "wave", "wave hello goodbye", true, "Wave", "Hands"),
    FamiliarArt("👏", "clap", "clap applause", true, "Clap", "Hands"),
    FamiliarArt("🙏", "thanks", "thanks pray please", true, "Thanks", "Hands"),
    FamiliarArt("✌️", "peace", "peace victory", true, "Peace", "Hands"),
    FamiliarArt("😄", "happy", "happy smile joy", false, "Happy", "Faces"),
    FamiliarArt("😂", "tears-of-joy", "tears of joy laugh funny lol", false, "Tears of joy", "Faces"),
    FamiliarArt("😍", "heart-eyes", "heart eyes love adore", false, "Heart eyes", "Faces"),
    FamiliarArt("😎", "cool", "cool sunglasses", false, "Cool", "Faces"),
    FamiliarArt("😉", "wink", "wink joke", false, "Wink", "Faces"),
    FamiliarArt("😘", "kiss", "kiss love", false, "Kiss", "Faces"),
    FamiliarArt("😢", "sad", "sad tear", false, "Sad", "Faces"),
    FamiliarArt("😭", "crying", "crying sob tears", false, "Crying", "Faces"),
    FamiliarArt("😠", "angry", "angry mad", false, "Angry", "Faces"),
    FamiliarArt("😮", "surprised", "surprised wow", false, "Surprised", "Faces"),
    FamiliarArt("🤔", "thinking", "thinking hmm question", false, "Thinking", "Faces"),
    FamiliarArt("😑", "unimpressed", "unimpressed meh", false, "Unimpressed", "Faces"),
    FamiliarArt("😁", "grin", "grin happy teeth", false, "Grin", "Faces"),
    FamiliarArt("🤣", "rolling-laughter", "rolling with laughter rofl funny", false, "Rolling with laughter", "Faces"),
    FamiliarArt("🥰", "love", "love hearts affection", false, "Love", "Faces"),
    FamiliarArt("😱", "shocked", "shocked scream fear", false, "Shocked", "Faces"),
    FamiliarArt("😴", "sleepy", "sleepy sleep tired", false, "Sleepy", "Faces"),
    FamiliarArt("😅", "phew", "phew relief sweat", false, "Phew", "Faces"),
    FamiliarArt("❤️", "heart", "heart love red", false, "Heart", "Symbols"),
    FamiliarArt("💔", "broken-heart", "broken heart sad", false, "Broken heart", "Symbols"),
    FamiliarArt("🔥", "fire", "fire hot flame", false, "Fire", "Symbols"),
    FamiliarArt("🎉", "celebrate", "celebrate party confetti", false, "Celebrate", "Symbols"),
    FamiliarArt("✅", "yes", "yes check tick correct", false, "Yes", "Symbols"),
    FamiliarArt("❌", "no", "no cross wrong", false, "No", "Symbols"),
    FamiliarArt("😀", "grinning", "grinning happy smile", false, "Grinning", "Faces"),
    FamiliarArt("🙂", "slight-smile", "slight smile friendly", false, "Slight smile", "Faces"),
    FamiliarArt("🙃", "upside-down", "upside down silly irony", false, "Upside down", "Faces"),
    FamiliarArt("😊", "blush", "blush happy shy", false, "Blush", "Faces"),
    FamiliarArt("😇", "innocent", "innocent angel halo", false, "Innocent", "Faces"),
    FamiliarArt("🥳", "party-face", "party face celebrate birthday", false, "Party face", "Faces"),
    FamiliarArt("🤩", "star-eyes", "star eyes excited amazed", false, "Star eyes", "Faces"),
    FamiliarArt("😋", "delicious", "delicious yum food", false, "Delicious", "Faces"),
    FamiliarArt("😛", "tongue", "tongue out playful", false, "Tongue out", "Faces"),
    FamiliarArt("😜", "wink-tongue", "winking tongue silly cheeky", false, "Winking tongue", "Faces"),
    FamiliarArt("🤪", "zany", "zany crazy silly", false, "Zany", "Faces"),
    FamiliarArt("🤑", "money-face", "money face rich cash", false, "Money face", "Faces"),
    FamiliarArt("🤐", "zip-mouth", "zipped mouth secret quiet", false, "Zipped mouth", "Faces"),
    FamiliarArt("🤨", "raised-eyebrow", "raised eyebrow sceptical doubt", false, "Raised eyebrow", "Faces"),
    FamiliarArt("😐", "neutral", "neutral blank", false, "Neutral", "Faces"),
    FamiliarArt("🙄", "eye-roll", "eye roll annoyed", false, "Eye roll", "Faces"),
    FamiliarArt("😏", "smirk", "smirk knowing", false, "Smirk", "Faces"),
    FamiliarArt("😬", "grimace", "grimace awkward teeth", false, "Grimace", "Faces"),
    FamiliarArt("😔", "pensive", "pensive sad thoughtful", false, "Pensive", "Faces"),
    FamiliarArt("🥺", "pleading", "pleading please puppy eyes", false, "Pleading", "Faces"),
    FamiliarArt("😤", "huff", "huff steam frustrated", false, "Huff", "Faces"),
    FamiliarArt("😡", "furious", "furious angry red", false, "Furious", "Faces"),
    FamiliarArt("🤯", "mind-blown", "mind blown exploding amazed", false, "Mind blown", "Faces"),
    FamiliarArt("🥵", "hot-face", "hot face heat sweat", false, "Hot face", "Faces"),
    FamiliarArt("🥶", "cold-face", "cold face frozen ice", false, "Cold face", "Faces"),
    FamiliarArt("🤢", "nauseated", "nauseated sick green", false, "Nauseated", "Faces"),
    FamiliarArt("🤮", "vomit", "vomiting sick", false, "Vomiting", "Faces"),
    FamiliarArt("🤒", "fever", "fever thermometer sick", false, "Fever", "Faces"),
    FamiliarArt("🤕", "bandage", "bandaged head hurt injury", false, "Bandaged head", "Faces"),
    FamiliarArt("😷", "mask", "medical mask ill health", false, "Medical mask", "Faces"),
    FamiliarArt("🐶", "dog", "dog puppy pet", false, "Dog", "Nature"),
    FamiliarArt("🐱", "cat", "cat kitten pet", false, "Cat", "Nature"),
    FamiliarArt("🐭", "mouse", "mouse rodent", false, "Mouse", "Nature"),
    FamiliarArt("🐹", "hamster", "hamster pet", false, "Hamster", "Nature"),
    FamiliarArt("🐰", "rabbit", "rabbit bunny", false, "Rabbit", "Nature"),
    FamiliarArt("🦊", "fox", "fox animal", false, "Fox", "Nature"),
    FamiliarArt("🐻", "bear", "bear animal", false, "Bear", "Nature"),
    FamiliarArt("🐼", "panda", "panda bear", false, "Panda", "Nature"),
    FamiliarArt("🐨", "koala", "koala animal", false, "Koala", "Nature"),
    FamiliarArt("🐯", "tiger", "tiger cat", false, "Tiger", "Nature"),
    FamiliarArt("🦁", "lion", "lion cat", false, "Lion", "Nature"),
    FamiliarArt("🐮", "cow", "cow farm", false, "Cow", "Nature"),
    FamiliarArt("🐷", "pig", "pig farm", false, "Pig", "Nature"),
    FamiliarArt("🐸", "frog", "frog green", false, "Frog", "Nature"),
    FamiliarArt("🐵", "monkey", "monkey animal", false, "Monkey", "Nature"),
    FamiliarArt("🐔", "chicken", "chicken bird", false, "Chicken", "Nature"),
    FamiliarArt("🐧", "penguin", "penguin bird", false, "Penguin", "Nature"),
    FamiliarArt("🦆", "duck", "duck bird", false, "Duck", "Nature"),
    FamiliarArt("🦉", "owl", "owl bird", false, "Owl", "Nature"),
    FamiliarArt("🦋", "butterfly", "butterfly insect", false, "Butterfly", "Nature"),
    FamiliarArt("🐝", "bee", "bee insect honey", false, "Bee", "Nature"),
    FamiliarArt("🐢", "turtle", "turtle slow", false, "Turtle", "Nature"),
    FamiliarArt("🐙", "octopus", "octopus sea", false, "Octopus", "Nature"),
    FamiliarArt("🐳", "whale", "whale sea", false, "Whale", "Nature"),
    FamiliarArt("🌻", "sunflower", "sunflower flower", false, "Sunflower", "Nature"),
    FamiliarArt("🌹", "rose", "rose flower love", false, "Rose", "Nature"),
    FamiliarArt("🌈", "rainbow", "rainbow weather", false, "Rainbow", "Nature"),
    FamiliarArt("☀️", "sun", "sun sunny weather", false, "Sun", "Nature"),
    FamiliarArt("🌙", "moon", "moon night", false, "Moon", "Nature"),
    FamiliarArt("⭐", "star", "star night favourite", false, "Star", "Nature"),
    FamiliarArt("🍎", "apple", "apple fruit", false, "Apple", "Food"),
    FamiliarArt("🍌", "banana", "banana fruit", false, "Banana", "Food"),
    FamiliarArt("🍓", "strawberry", "strawberry fruit", false, "Strawberry", "Food"),
    FamiliarArt("🍉", "watermelon", "watermelon fruit", false, "Watermelon", "Food"),
    FamiliarArt("🍋", "lemon", "lemon fruit", false, "Lemon", "Food"),
    FamiliarArt("🥑", "avocado", "avocado food", false, "Avocado", "Food"),
    FamiliarArt("🍕", "pizza", "pizza food slice", false, "Pizza", "Food"),
    FamiliarArt("🍔", "burger", "burger food", false, "Burger", "Food"),
    FamiliarArt("🍟", "fries", "fries chips food", false, "Fries", "Food"),
    FamiliarArt("🌮", "taco", "taco food", false, "Taco", "Food"),
    FamiliarArt("🍿", "popcorn", "popcorn movie snack", false, "Popcorn", "Food"),
    FamiliarArt("🍰", "cake", "cake dessert birthday", false, "Cake", "Food"),
    FamiliarArt("🍩", "doughnut", "doughnut donut dessert", false, "Doughnut", "Food"),
    FamiliarArt("🍪", "cookie", "cookie biscuit snack", false, "Cookie", "Food"),
    FamiliarArt("🍦", "ice-cream", "ice cream dessert", false, "Ice cream", "Food"),
    FamiliarArt("☕", "coffee", "coffee tea drink", false, "Coffee", "Food"),
    FamiliarArt("🍺", "beer", "beer pint drink", false, "Beer", "Food"),
    FamiliarArt("🥂", "cheers", "cheers glasses toast", false, "Cheers", "Food"),
    FamiliarArt("🎁", "gift", "gift present birthday", false, "Gift", "Objects"),
    FamiliarArt("💡", "idea", "light bulb idea", false, "Light bulb", "Objects"),
    FamiliarArt("🔑", "key", "key unlock", false, "Key", "Objects"),
    FamiliarArt("🔒", "lock", "lock private secure", false, "Lock", "Objects"),
    FamiliarArt("🚀", "rocket", "rocket launch space", false, "Rocket", "Objects"),
    FamiliarArt("💻", "laptop", "laptop computer work", false, "Laptop", "Objects"),
    FamiliarArt("📱", "phone", "phone mobile", false, "Phone", "Objects"),
    FamiliarArt("📷", "camera", "camera photo", false, "Camera", "Objects"),
    FamiliarArt("🎮", "gamepad", "gamepad game play", false, "Gamepad", "Objects"),
    FamiliarArt("⚽", "football", "football soccer sport", false, "Football", "Objects"),
    FamiliarArt("🏆", "trophy", "trophy winner award", false, "Trophy", "Objects"),
    FamiliarArt("💩", "poop", "poop shit poo", false, "Poop", "Objects"),
    FamiliarArt("🫏", "crypto-donkey", "donkey orange crypto cryptodonkey thecryptodonkey cute mascot", false, "Donkey", "Nature"),
    FamiliarArt("🪨", "sacred-stone", "rock stone sacred 600 600.wtf 600000000000", false, "Sacred stone", "Objects"),
    FamiliarArt("🕷️", "jumping-spider", "jumping spider black spider cute littleleap little leap pip jumping fuzzy", false, "Jumping spider", "Nature"),
    FamiliarArt("₿", "bitcoin", "bitcoin btc orange coin currency", false, "Bitcoin", "Symbols"),
    FamiliarArt(":fs_forgesworn:", "fs-forgesworn", "forgesworn forgesworn brand logo forgesworn", false, "ForgeSworn", "forgesworn"),
    FamiliarArt(":fs_kindred:", "fs-kindred", "kindred forgesworn brand logo kindred", false, "Kindred", "forgesworn"),
    FamiliarArt(":fs_kithmoot:", "fs-kithmoot", "kithmoot forgesworn brand logo kithmoot", false, "KithMoot", "forgesworn"),
    FamiliarArt(":fs_mysignet:", "fs-mysignet", "mysignet forgesworn brand logo mysignet", false, "MySignet", "forgesworn"),
    FamiliarArt(":fs_vitark:", "fs-vitark", "vitark forgesworn brand logo vitark", false, "Vitark", "forgesworn"),
    FamiliarArt(":fs_vitark_den:", "fs-vitark-den", "vitark den forgesworn brand logo vitark den", false, "Vitark Den", "forgesworn"),
    FamiliarArt(":fs_vitark_train:", "fs-vitark-train", "vitark train forgesworn brand logo vitark train", false, "Vitark Train", "forgesworn"),
    FamiliarArt(":fs_vitark_still:", "fs-vitark-still", "vitark still forgesworn brand logo vitark still", false, "Vitark Still", "forgesworn"),
    FamiliarArt(":fs_vitark_record:", "fs-vitark-record", "vitark record forgesworn brand logo vitark record", false, "Vitark Record", "forgesworn"),
)
val HUMAN_SKIN_TONES = listOf("", "🏻", "🏼", "🏽", "🏾", "🏿")
fun withSkinTone(emoji: String, tone: Int): String {
    require(tone in HUMAN_SKIN_TONES.indices)
    return if (tone == 0 || FAMILIAR_ART.none { it.emoji == emoji && it.toneable }) emoji else emoji.replace("\uFE0F", "") + HUMAN_SKIN_TONES[tone]
}
