package dev.forgesworn.kithmoot.relay

import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNull

class Nip77NegentropyTest {
    @Test fun `empty initiation is the NIP-77 V1 empty ID range`() {
        val sync = Nip77Negentropy(emptyList())
        assertContentEquals(hex("6100000200"), sync.initiate())
    }

    @Test fun `a relay ID becomes need without an automatic next message`() {
        val sync = Nip77Negentropy(emptyList())
        sync.initiate()
        val result = sync.reconcile(hex("6100000201" + "bb".repeat(32)))
        assertEquals(listOf("bb".repeat(32)), result.need.map(::hex))
        assertEquals(emptyList(), result.have)
        assertNull(result.nextMessage)
    }

    @Test fun `a local only ID becomes have`() {
        val sync = Nip77Negentropy(listOf(Nip77Record(5u, hex("aa".repeat(32)))))
        assertContentEquals(hex("6100000201" + "aa".repeat(32)), sync.initiate())
        val result = sync.reconcile(hex("6100000200"))
        assertEquals(listOf("aa".repeat(32)), result.have.map(::hex))
        assertEquals(emptyList(), result.need)
        assertNull(result.nextMessage)
    }

    @Test fun `the local window is bounded before a message is made`() {
        val records = (0..Nip77Negentropy.MAX_RECORDS).map { Nip77Record(it.toULong(), ByteArray(32) { it.toByte() }) }
        assertFailsWith<IllegalArgumentException> { Nip77Negentropy(records) }
    }

    @Test fun `matches the pinned Bothy Rust negentropy transcript across fingerprint buckets`() {
        val client = (1..40).map { number -> Nip77Record(number.toULong(), ByteArray(32) { number.toByte() }) }
        val sync = Nip77Negentropy(client)
        // Generated by the 0.5.1 negentropy crate Bothy pins for its NIP-77 relay.
        assertContentEquals(hex(
            "61050001c07a25db62a65dc5477decb10bf5f293040001ed67b1878122dd0b254bca97d1c838260" +
                "40001730ad5e9c0f68298798d4b5a7fdf0ba90400018ed01fbe9f7bb49a2428d0a550646238040001" +
                "05aa3fad752a4b6d179d48fff78fbe720400016df1c5ccd3827fb5dec64984b7050d6004000137a91a" +
                "387ad57a55c6fe0a229bdaf89d040001bdb50f7821be5751c677a08fb8bd8b5a030001cd20b9f83aa18e" +
                "89dd323257ca0a6e090300012198850980141c511aed175878f65040030001ca3d66888b97cac95e0895" +
                "1fff742c9703000115e52dde58a3e1e3e713e9cd6524dd88030001a2193a3264bb54d8d1c0dcf5fda02d" +
                "4a0300013bb3a4fcbe198223e9e1c3efd589bd7f030001d96beaa8225e7843b51e9b0e2fcb0d10000001d" +
                "9cb12a836487c8eeefcf62051a9f232",
        ), sync.initiate())
        val result = sync.reconcile(hex(
            "6108000004000202" + "07".repeat(32) + "09".repeat(32) +
                "18000003000201" + "22".repeat(32) + "05000000000204" +
                "27".repeat(32) + "28".repeat(32) + "63".repeat(32) + "64".repeat(32),
        ))
        assertEquals(listOf("08".repeat(32), "21".repeat(32)), result.have.map(::hex))
        // Rust's HashSet makes this output order deliberately unspecified;
        // the Android primitive keeps the relay's wire order for stable UI.
        assertEquals(listOf("63".repeat(32), "64".repeat(32)), result.need.map(::hex))
        assertNull(result.nextMessage)
    }

    @Test fun `malformed or non canonical relay frames fail closed`() {
        val sync = Nip77Negentropy(emptyList())
        sync.initiate()
        assertFailsWith<Nip77ProtocolException> { sync.reconcile(hex("62")) }
        assertFailsWith<Nip77ProtocolException> { sync.reconcile(hex("618000000200")) }
        assertFailsWith<Nip77ProtocolException> { sync.reconcile(hex("61000003")) }
    }

    private fun hex(value: String): ByteArray = value.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
    private fun hex(value: ByteArray) = value.joinToString("") { "%02x".format(it.toInt() and 0xff) }
}
